// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Store.Models
{
    public partial class CartProduct
    {
        public int IdCartProduct { get; set; }
        public int IdCart { get; set; }
        public int IdProduct { get; set; }
        public int Amout { get; set; }

        public virtual Cart IdCartNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
    }
}