// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Store.Models
{
    public partial class Product
    {
        public Product()
        {
            AvailableProducts = new HashSet<AvailableProduct>();
            CartProducts = new HashSet<CartProduct>();
        }

        public int IdProduct { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }

        public virtual ICollection<AvailableProduct> AvailableProducts { get; set; }
        public virtual ICollection<CartProduct> CartProducts { get; set; }
    }
}