// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Online_Store.Models
{
    public partial class User: IdentityUser<int>
    {
        public User()
        {
            Carts = new HashSet<Cart>();
        }

        public int IdUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
   
      
        

        public virtual ICollection<Cart> Carts { get; set; }
    }
}